// Generated by scripts/build-addon-types.mjs. Do not edit.
// Run `npm run build:addon-types` after changing the addon surface.

/** What the in-page editor is told about the API an addon may reach. */
export const ADDON_SURFACE_TYPES = `declare module 'fathom' {
    // addon-api.d.ts
    /**
     * Everything an addon may reach, and nothing else.
     *
     * One file so the surface is a list somebody can read, and so widening it is a
     * deliberate edit rather than a stray export somewhere in the tree.
     */
    /**
     * Starts a plan, bound to the bars every series lines up with.
     *
     * @example
     * Plot.over(input.bars).line(mean, 'Mean').in('amber').overThePrice()
     */
    export declare const Plot: {
        readonly over: typeof plotOver;
    };
    /**
     * The knobs a reading offers, each already a usable parameter as it is built.
     *
     * @example
     * Params.integer('periodBars').called('Period').between(2, 400).startingAt(20)
     */
    export declare const Params: {
        readonly integer: typeof integerParameter;
        readonly decimal: typeof decimalParameter;
        readonly choice: typeof choiceParameter;
        readonly toggle: typeof toggleParameter;
    };

    // bar-source.d.ts
    /**
     * Which figure of a bar an indicator is run over.
     *
     * The closing price is what most readings mean by "the price", but not all of
     * them: a channel drawn on the midpoint of each bar sits differently from one
     * drawn on where trading happened to stop.
     */
    export declare const BAR_SOURCES: readonly ["close", "open", "high", "low", "hl2", "hlc3", "ohlc4"];
    export type BarSource = typeof BAR_SOURCES[number];
    export declare const SOURCE: ChoiceParameter;
    /**
     * The figure a bar contributes under a chosen source.
     *
     * @param bar - The bar to read.
     * @param source - Which figure, or which blend of them.
     * @returns The value the indicator sees.
     */
    export declare function readBarSource(bar: PriceBar, source: BarSource): number;
    /**
     * The chosen source of every bar in a window.
     *
     * @param bars - The window, oldest first.
     * @param settings - The reader's parameter values.
     * @returns One figure per bar, in order.
     */
    export declare function collectSource(bars: readonly PriceBar[], settings: IndicatorSettings): Float64Array;

    // depth-types.d.ts
    /** A price level as the venue serializes it, before any numeric parsing. */
    export type SerializedPriceLevel = readonly [price: string, quantity: string];
    /**
     * One incremental depth update, in venue-neutral terms.
     */
    export interface DepthDiff {
        readonly firstUpdateId: number;
        readonly finalUpdateId: number;
        readonly previousFinalUpdateId: number;
        readonly bidLevels: readonly SerializedPriceLevel[];
        readonly askLevels: readonly SerializedPriceLevel[];
    }
    /** A full depth ladder captured at one point in the venue's update sequence. */
    export interface DepthSnapshot {
        readonly lastUpdateId: number;
        readonly bidLevels: readonly SerializedPriceLevel[];
        readonly askLevels: readonly SerializedPriceLevel[];
    }
    /** One aggressive execution, in venue-neutral terms. */
    export interface ExecutedTrade {
        readonly executedAtMs: number;
        readonly price: number;
        readonly quantity: number;
        readonly isAggressorSelling: boolean;
    }
    /** The two prices that separate resting bids from resting asks. */
    export interface TopOfBook {
        readonly bestBidPrice: number;
        readonly bestAskPrice: number;
    }
    /** A consistent read of the local book. */
    export interface OrderBookReading extends TopOfBook {
        readonly bidQuantityByPrice: ReadonlyMap<number, number>;
        readonly askQuantityByPrice: ReadonlyMap<number, number>;
    }

    // draw-plan.d.ts
    /**
     * Colours an indicator may ask for, as tokens rather than CSS.
     *
     * A token because the host resolves it against the palette in force: a plan that
     * named a colour would be wrong the moment the reader switched theme, and a plan
     * is held between frames.
     */
    export type PlotTone = 'bid' | 'ask' | 'amber' | 'phosphor' | 'violet' | 'cyan' | 'ink' | 'muted';
    /** Every tone a plan may name. */
    export declare const PLOT_TONES: readonly PlotTone[];
    /**
     * The tones one added copy can be given to tell it from another.
     *
     * A subset rather than the whole list: \`bid\` sits too close to \`phosphor\` to
     * separate two lines crossing each other, and \`muted\` is what an accent is
     * drawn in, so neither can carry an identity.
     */
    /**
     * The colours a copy is identified by, in the order they are handed out.
     *
     * Neither side of the book is in here. Green means buying and red means the
     * offer everywhere else on this chart — the candles, the volume, the delta, the
     * heat ramp, the resistances of a pivot set — so handing one of them to a mean
     * as an identity teaches a reader something false about a line that has no side
     * at all.
     *
     * Five, and a reader with more copies than that gets a colour twice. That is
     * the point where colour has stopped being able to say which line is which, and
     * it is why a plan can write its own names on the chart instead.
     */
    /**
     * How a series is drawn.
     *
     * \`dot\` is not a thin line. A reading that flips from one side of price to the
     * other says so by where its marks sit, and joining them up draws a stroke
     * through the price at every flip that no reading ever took.
     */
    export type PlotShape = 'line' | 'histogram' | 'dot';
    /**
     * One plotted series, as vertices in data space.
     *
     * Never in pixels. The host owns the only function from a value to a pixel, so
     * a pan re-projects a plan it already holds instead of asking for a new one —
     * which is what keeps author code off the gesture path entirely.
     */
    export interface PlotSeries {
        /**
         * Names the series in the legend.
         *
         * Resolved against the catalogue when it matches an entry and rendered as
         * written when it does not, so an addon can ship a label the host has never
         * heard of without shipping a translation for it.
         */
        readonly label: string;
        readonly tone: PlotTone;
        readonly shape: PlotShape;
        /** Instants, ascending. Same length as \`value\`. */
        readonly atMs: Float64Array;
        /** NaN where the series has nothing to say, so a line breaks instead of bridging. */
        readonly value: Float64Array;
        /** Used below \`baseline\`. Absent means one colour throughout. */
        readonly negativeTone?: PlotTone;
        /** Where a histogram grows from. Ignored by lines. */
        readonly baseline?: number;
        readonly widthPx?: number;
        readonly isDashed?: boolean;
    }
    /**
     * A shaded region between two of the plan's series.
     */
    export interface PlotBand {
        readonly tone: PlotTone;
        readonly upperSeriesIndex: number;
        readonly lowerSeriesIndex: number;
    }
    /**
     * A horizontal line at a constant value.
     */
    export interface PlotLevel {
        readonly value: number;
        readonly tone: PlotTone;
        readonly isDashed?: boolean;
    }
    /**
     * Which vertical scale a plan is drawn against.
     *
     * \`price\` puts it over the chart on the price's own axis. \`overlay\` puts it
     * along the bottom of the same pane on a scale of its own. The rest give it a
     * band, because a quantity that is not a price cannot share an axis with one:
     * an oscillator bounded to 0..100 plotted against a price axis is a flat line
     * at the bottom of the screen.
     */
    export type PlotScale = {
        readonly kind: 'price';
    }
    /**
     * A strip along the bottom of the price pane, on a scale of its own.
     *
     * For a reading that belongs beside the price without being one and without
     * being worth a band: it costs the price no height, only some of its floor.
     */
     | {
        readonly kind: 'overlay';
        readonly heightRatio: number;
    } | {
        readonly kind: 'auto';
    } | {
        readonly kind: 'fixed';
        readonly low: number;
        readonly high: number;
    } | {
        readonly kind: 'symmetric';
    };
    /**
     * What an indicator returns for one window.
     *
     * Only what the arithmetic produced; the host stamps on everything it already
     * knew, so a name or a scale cannot have two answers.
     */
    export interface PlanDraft {
        readonly series: readonly PlotSeries[];
        readonly bands?: readonly PlotBand[];
        readonly levels?: readonly PlotLevel[];
        /**
         * Whether each series is written at the end of its own line.
         *
         * For a plan whose series are only meaningful named. A set of levels is
         * the case that forced it: seven lines in three colours, two of them
         * necessarily alike, say "some red ones above and some green ones below"
         * and nothing else — where the reading a floor actually takes is that
         * price is testing R2 and not R3. Almost nothing else wants it, because a
         * mean and its channel are told apart by where they are.
         */
        readonly namesItsSeries?: boolean;
        /**
         * Whether the output can be trusted at its left edge.
         *
         * Defaulted by the host to whether the warm-up asked for arrived. Declared
         * here only where a reading converges on something else — an anchor to
         * find, a session to see turn over.
         */
        readonly hasConverged?: boolean;
        /**
         * The knobs as the legend should show them.
         *
         * Defaulted by the host to the figures the reader turned. Declared here
         * only where the useful summary is not those.
         */
        readonly parameterSummary?: string;
        /**
         * The axis this window's values belong on.
         *
         * Defaulted by the host to the one the indicator declared. Declared here
         * only where the axis depends on how the reading was tuned.
         */
        readonly scale?: PlotScale;
    }
    /**
     * A draft with everything the host knows stamped on.
     *
     * What the painters are given, and what a reader's controls reach.
     */
    export interface DrawPlan extends PlanDraft {
        readonly indicatorId: string;
        /**
         * Which added copy produced it, stamped by the host rather than the author.
         *
         * An indicator has no idea how many times a reader has added it, and the
         * controls over a plan have to reach the one copy they belong to.
         */
        readonly instanceId?: string;
        /**
         * Which band it shares, stamped by the host rather than the author.
         *
         * An indicator has no idea what else is on the chart, and whether two
         * readings belong side by side is the reader's judgement, not its own.
         */
        readonly bandKey?: string;
        /**
         * What it was produced from, stamped by the host rather than the author.
         *
         * The drawn layer is held between frames and repainted only when its
         * description changes. A recolour or a different source changes the
         * drawing and nothing else about it, so without this the canvas keeps
         * showing the previous one.
         */
        readonly tuning?: string;
        readonly label: string;
        /** The parameters that produced it, as the legend shows them. */
        readonly parameterSummary: string;
        readonly scale: PlotScale;
        /**
         * Whether the plan's own colours carry a reading rather than an identity.
         *
         * Volume is drawn green and red because the bar rose or fell, not because
         * it is the first copy on the chart. Painting such a plan in the colour a
         * copy is identified by would say something untrue about the data.
         */
        readonly isSelfColoured?: boolean;
        readonly hasConverged: boolean;
    }
    /**
     * A knob that takes a figure.
     */
    export interface NumericParameter {
        readonly name: string;
        /** What the control is called. Absent falls back to a key built from the name. */
        readonly label?: string;
        readonly kind: 'integer' | 'decimal';
        readonly defaultValue: number;
        readonly minimum: number;
        readonly maximum: number;
        /**
         * How far one nudge moves it.
         *
         * Declared where the useful travel is not spread evenly across the range:
         * the upper cut of the depth map lives in its last percent, and a step
         * sized to the whole range would offer two positions inside it.
         */
        readonly step?: number;
    }
    /**
     * A knob that takes one of a fixed set of answers.
     */
    export interface ChoiceParameter {
        readonly name: string;
        /** What the control is called. Absent falls back to a key built from the name. */
        readonly label?: string;
        readonly kind: 'choice';
        readonly defaultValue: string;
        readonly choices: readonly string[];
    }
    /**
     * A knob that is either on or off.
     */
    export interface ToggleParameter {
        readonly name: string;
        /** What the control is called. Absent falls back to a key built from the name. */
        readonly label?: string;
        readonly kind: 'toggle';
        readonly defaultValue: boolean;
    }
    export type IndicatorParameter = NumericParameter | ChoiceParameter | ToggleParameter;
    /** Anything with knobs a reader can turn, whoever draws it. */
    export interface Tunable {
        readonly parameters: readonly IndicatorParameter[];
    }
    /** Parameter values by name. */
    export type IndicatorSettings = Readonly<Record<string, number | string | boolean>>;
    /**
     * A coarser session an indicator also reads, and how far back it needs them.
     *
     * The reach is in sessions of the rung asked for, not bars of the one drawn:
     * fifty daily closes is fifty days on a minute chart and on an hourly one.
     */
    export interface SessionRequest {
        readonly intervalMs: number;
        /** Settled sessions needed before the window opens. */
        readonly reachingBack: number;
    }
    /**
     * Everything besides the drawn bars a reading needs, for the host to fetch.
     *
     * One method rather than one per kind: it is one question, and the host merges
     * every answer on the chart in a single pass.
     */
    export interface SourceRequest {
        /** Bars before the drawn window, on the drawn rung. */
        readonly warmupBars?: number;
        /**
         * Coarser sessions, keyed by the name \`compute\` reads them back under.
         *
         * Named rather than keyed by the figure asked with, so declaring and
         * looking one up is the same string.
         */
        readonly sessions?: Readonly<Record<string, SessionRequest>>;
        /**
         * Facts about the venue this reading cannot be computed without.
         *
         * The same sentence as the rungs above, about the venue rather than about
         * the window: a reading that divides by the taker split is arithmetic on a
         * figure a venue may not publish, and one that shades between resting
         * prices is drawing a place a windowed feed never described. Declared, the
         * reading is put out of reach on a venue that cannot answer it. Undeclared,
         * it is offered and draws a plausible flat line over the absence.
         */
        readonly needs?: readonly VenueFact[];
    }
    /**
     * A coarser rung, aligned to the drawn bars and held back to what each knew.
     *
     * Aligned rather than handed over whole because there is then no index that
     * reaches a session a drawn bar could not have seen.
     */
    export interface SettledSessions {
        /** False where no session had closed by any drawn bar. */
        readonly hasAny: boolean;
        /**
         * One entry per drawn bar: the newest session that had closed by its open.
         *
         * Undefined at the left edge, before anything had settled.
         */
        readonly perBar: readonly (PriceBar | undefined)[];
        /** 1 where a drawn bar is the first after the session turned over. */
        readonly turnsOver: Uint8Array;
        /**
         * Every session that had settled, oldest first, back as far as was asked.
         *
         * \`perBar\` answers "what did this drawn bar know", which is one bar. This
         * answers "what is there to work from", which is the run of them — and a
         * mean over a coarser rung needs the run. Without it a fifty-period mean
         * could only be built from the sessions that happened to turn over inside
         * the drawn window, which on a minute chart is one day and no weeks.
         *
         * Reaches back by \`reachingBack\` sessions before the window opens. Nothing
         * still forming is in here: the newest is the newest that had closed by the
         * last drawn bar, so widening the window cannot change what an earlier bar
         * was told.
         */
        readonly closed: readonly PriceBar[];
        /**
         * One entry per drawn bar: where in \`closed\` its own session sits.
         *
         * -1 before the first one settled. Carried rather than left to be searched
         * for, because holding a figure computed over \`closed\` at each drawn bar is
         * the whole point of having both, and matching the bars by identity is a
         * scan per drawn bar.
         */
        readonly indexPerBar: Int32Array;
    }
    /** What a reading with no sessions declared is handed under any name. */
    export declare const NO_SESSIONS: SettledSessions;
    export interface IndicatorInput {
        readonly bars: PriceBarWindow;
        readonly settings: IndicatorSettings;
        /**
         * The coarser sessions declared, by name.
         *
         * Plain data so the whole input survives being sent to a worker, which
         * strips the prototype off anything carrying methods.
         */
        readonly sessions: Readonly<Record<string, SettledSessions>>;
    }
    /**
     * A declared session, by name.
     *
     * @param input - What the reading was handed.
     * @param name - The key the session was declared under.
     * @returns The sessions, held back to what each drawn bar could know.
     * @throws Error when nothing was declared under that name, which is louder
     *     than the flat line an empty one would draw.
     */
    export declare function readSessions(input: IndicatorInput, name: string): SettledSessions;
    /**
     * One indicator: a description of its knobs, and a pure function from bars to vertices.
     *
     * Stateless on purpose. The settings arrive with the call rather than with a
     * constructor, so the same object serves every copy a reader has added and
     * nothing has to be rebuilt when one of them is retuned.
     */
    /**
     * A layer the host draws itself, rather than one built from arithmetic.
     *
     * The depth map is the reason this exists. It is a picture of hundreds of
     * thousands of cells built from the book, not a handful of vertices built from
     * bars, and it is painted on a layer of its own so that dragging the chart is a
     * blit rather than a repaint. None of that fits what an indicator returns.
     *
     * What it does share with an indicator is everything the reader touches: it is
     * added, tuned, hidden and removed the same way, from the same list.
     */
    export interface FieldLayer {
        readonly label: string;
        /** One line for the palette. A phrase, or a key naming one. */
        readonly about?: string;
        readonly parameters: readonly IndicatorParameter[];
    }
    /**
     * Anything a reader can add, paired with the id it is stored and found under.
     *
     * On the entry rather than on the reading, so the catalogue is the one place a
     * name is claimed and two readings cannot claim the same one.
     */
    export interface Registered<T> {
        readonly id: string;
        readonly layer: T;
    }
    export interface Indicator {
        /**
         * What the reading is called.
         *
         * A phrase, or a key naming one: unmatched keys render as written, so a
         * reading can ship a name without shipping a translation.
         */
        readonly label: string;
        /** One line for the palette. A phrase, or a key naming one. */
        readonly about?: string;
        /** Where it is drawn. Absent gives it a band of its own. */
        readonly scale?: PlotScale;
        /** Whether what it draws is told by its colour, so a copy cannot be tinted. */
        readonly isSelfColoured?: boolean;
        readonly parameters: readonly IndicatorParameter[];
        /** Everything besides the drawn bars this reads. Absent means the bars alone. */
        resolveSources?(settings: IndicatorSettings): SourceRequest;
        compute(input: IndicatorInput): PlanDraft;
    }
    /**
     * Limits a plan is held to, whoever produced it.
     *
     * An over-budget plan is rejected whole rather than truncated: half a series is
     * a different claim than the one the author made.
     *
     * The series cap was four while every reading here was a line, a pair of them,
     * or a line with a band. A set of levels is neither: a pivot set is seven lines
     * that only mean anything together, and drawing three of them is not a smaller
     * version of the reading. Eight is that set with room to spare, and still few
     * enough that the legend stays a legend.
     */
    export declare const PLOT_BUDGET: {
        readonly maximumSeriesCount: 8;
        readonly maximumVerticesPerSeries: 8192;
    };
    /**
     * Whether a plan is within what the host will draw.
     *
     * @param plan - The draft to check.
     * @returns True when every series fits the budget and every reference resolves.
     */
    export declare function isPlanWithinBudget(plan: PlanDraft): boolean;
    /**
     * Reads a figure, falling back to what the indicator declared.
     *
     * Clamped rather than trusted: a setting outlives the control that produced it,
     * so a figure no current control could produce still has to arrive safely.
     *
     * @param settings - Values the reader chose.
     * @param parameter - The knob being read.
     * @returns The value, clamped to the declared range and rounded when integral.
     */
    export declare function readSetting(settings: IndicatorSettings, parameter: NumericParameter): number;
    /**
     * Reads a switch, falling back to what the indicator declared.
     *
     * @param settings - Values the reader chose.
     * @param parameter - The knob being read.
     * @returns Whether it is on.
     */
    export declare function readToggle(settings: IndicatorSettings, parameter: ToggleParameter): boolean;
    /**
     * Reads a choice, falling back to what the indicator declared.
     *
     * @param settings - Values the reader chose.
     * @param parameter - The knob being read.
     * @returns One of the declared choices.
     */
    export declare function readChoice(settings: IndicatorSettings, parameter: ChoiceParameter): string;
    /**
     * The bars a reading needs before the drawn window.
     *
     * @param indicator - The reading being asked.
     * @param settings - Values the reader chose.
     * @returns The count, or none where it declared no sources at all.
     */
    /** What the host completes a draft with. */
    export interface PlanStamp {
        /** The id the copy was added under. */
        readonly indicatorId: string;
        readonly indicator: Indicator;
        readonly settings: IndicatorSettings;
        /** Bars of warm-up the archive actually supplied. */
        readonly warmupBarCount: number;
    }
    /**
     * Completes a draft with everything the host already knew.
     *
     * @param stamp - Who asked, how it was tuned, and what warm-up arrived.
     * @param draft - What the arithmetic produced.
     * @returns The plan the painters are given.
     */
    /**
     * The knobs a legend shows, for a plan that did not say.
     *
     * Figures only: a choice is usually what a reading is rather than how it was
     * tuned, and the name already says it.
     *
     * @param parameters - The knobs the indicator declared.
     * @param settings - Values the reader chose.
     * @returns The figures, in declaration order, or an empty string where none.
     */
    export declare function summariseParameters(parameters: readonly IndicatorParameter[], settings: IndicatorSettings): string;
    /**
     * Recolours a plan to the tone its copy was given.
     *
     * A plan that says its colours are a reading is left alone. Otherwise only what
     * was drawn in the indicator's own colour moves: a tone the author chose to
     * differ — a dashed midline, a signal line, the shading of a band —
     * is an accent that says something about the reading, and flattening those into
     * one colour would lose what the author was distinguishing.
     *
     * @param plan - What the indicator produced.
     * @param tone - The colour this copy is identified by.
     * @returns The plan, with its own colour replaced.
     */
    /**
     * The value a series carried at an instant.
     *
     * The bar the instant falls in rather than the nearest vertex: a reading
     * belongs to the bucket it was computed over, and rounding to the closer
     * neighbour would show the next bar's value for half of this one.
     *
     * @param series - The series to read.
     * @param atMs - The instant asked about.
     * @returns The value, or NaN where the series says nothing there.
     */

    // parameter-builder.d.ts
    /**
     * A figure knob under construction.
     *
     * Every step returns a whole, valid parameter rather than something needing a
     * closing call, so there is no build step to forget.
     */
    export interface NumericBuilder extends NumericParameter {
        /** What the control is called. A phrase, or a key naming one. */
        called(label: string): NumericBuilder;
        /** The range the reader can travel, which a stored value is clamped to. */
        between(minimum: number, maximum: number): NumericBuilder;
        /** How far one nudge moves it. */
        by(step: number): NumericBuilder;
        /** Where it starts. */
        startingAt(defaultValue: number): NumericBuilder;
    }
    /** A knob that takes one of a fixed set of answers, under construction. */
    export interface ChoiceBuilder extends ChoiceParameter {
        called(label: string): ChoiceBuilder;
        startingAt(defaultValue: string): ChoiceBuilder;
    }
    /** A switch, under construction. */
    export interface ToggleBuilder extends ToggleParameter {
        called(label: string): ToggleBuilder;
        startingAt(defaultValue: boolean): ToggleBuilder;
    }
    /**
     * A whole-number knob.
     *
     * @param name - The key its value is stored under.
     * @returns A builder that is already a usable parameter.
     */
    export declare function integerParameter(name: string): NumericBuilder;
    /**
     * A knob that takes a fraction.
     *
     * @param name - The key its value is stored under.
     * @returns A builder that is already a usable parameter.
     */
    export declare function decimalParameter(name: string): NumericBuilder;
    /**
     * A knob that takes one of a fixed set of answers.
     *
     * @param name - The key its value is stored under.
     * @param choices - What the reader may pick, the first being the default.
     * @returns A builder that is already a usable parameter.
     */
    export declare function choiceParameter(name: string, choices: readonly string[]): ChoiceBuilder;
    /**
     * A knob that is either on or off.
     *
     * @param name - The key its value is stored under.
     * @returns A builder that is already a usable parameter.
     */
    export declare function toggleParameter(name: string): ToggleBuilder;

    // plot-builder.d.ts
    /** Values a series can be given, whichever array the arithmetic produced. */
    export type PlotValues = ArrayLike<number>;
    /**
     * A plan under construction, bound to the bars its values line up with.
     *
     * Fluent because the raw draft has thirteen fields and an author cares about
     * two; the rest are ways to be wrong quietly. Nothing here is a translation —
     * every method sets a field on the object the host was always going to be
     * given, so anything this does not cover is reachable by writing that object.
     */
    export declare class PlotBuilder {
        private readonly atMs;
        private readonly series;
        private readonly bands;
        private readonly levels;
        private isNamingLines;
        private ownSummary;
        private ownConvergence;
        constructor(bars: PriceBarWindow);
        /**
         * Adds a line.
         *
         * @param values - One per drawn bar. NaN breaks the line rather than bridging.
         * @param label - What the legend calls it.
         * @returns This builder.
         */
        line(values: PlotValues, label?: string): this;
        /**
         * Adds a histogram.
         *
         * @param values - One per drawn bar.
         * @param label - What the legend calls it.
         * @returns This builder.
         */
        histogram(values: PlotValues, label?: string): this;
        /**
         * Adds a series of marks that are not joined up.
         *
         * For a reading that flips from one side of price to the other: joining the
         * marks draws a stroke through the price at every flip that no reading took.
         *
         * @param values - One per drawn bar.
         * @param label - What the legend calls it.
         * @returns This builder.
         */
        dots(values: PlotValues, label?: string): this;
        /**
         * Adds one line per entry, in the order given.
         *
         * @param named - Values by the name each is drawn under.
         * @returns This builder.
         */
        lines(named: Readonly<Record<string, PlotValues>>): this;
        /**
         * Colours the series added last.
         *
         * @param tone - A token from the palette, never a CSS colour.
         * @returns This builder.
         */
        in(tone: PlotTone): this;
        /**
         * Draws the series added last as a broken line.
         *
         * @returns This builder.
         */
        dashed(): this;
        /**
         * Sets how thick the series added last is drawn.
         *
         * @param widthPx - Stroke width.
         * @returns This builder.
         */
        thick(widthPx: number): this;
        /**
         * Splits the series added last by side about a baseline.
         *
         * @param baseline - Where it grows from.
         * @returns This builder.
         */
        risingAndFalling(baseline?: number): this;
        /**
         * Shades the region between two series.
         *
         * @param upper - Index of the series above.
         * @param lower - Index of the series below.
         * @param tone - What to shade it in. Defaults to the upper series' tone.
         * @returns This builder.
         */
        shading(upper: number, lower: number, tone?: PlotTone): this;
        /**
         * Draws a horizontal line at a constant value.
         *
         * @param value - Where it sits.
         * @param tone - What to draw it in.
         * @returns This builder.
         */
        at(value: number, tone?: PlotTone): this;
        /**
         * Writes each series' name at the end of its own line.
         *
         * For a plan whose series only mean anything named — a set of levels says
         * "some above and some below" unless the reader can see which is which.
         *
         * @returns This builder.
         */
        namingEachLine(): this;
        /**
         * Replaces what the legend shows for the knobs.
         *
         * @param summary - What to show instead of the figures the reader turned.
         * @returns This builder.
         */
        summarisedAs(summary: string): this;
        /**
         * States whether the output can be trusted at its left edge.
         *
         * Only for a reading that converges on something other than a bar count —
         * an anchor to find, a session to see turn over.
         *
         * @param hasConverged - Whether the left edge is true.
         * @returns This builder.
         */
        converged(hasConverged: boolean): this;
        /** Draws it over the chart, on the price's own axis. */
        overThePrice(): PlanDraft;
        /** Gives it a band of its own, scaled to what it drew. */
        inItsOwnBand(): PlanDraft;
        /**
         * Gives it a band with fixed bounds.
         *
         * @param low - The floor of the axis.
         * @param high - The ceiling.
         * @returns The finished draft.
         */
        between(low: number, high: number): PlanDraft;
        /** Gives it a band centred on nought, so equal opposites read alike. */
        aboutZero(): PlanDraft;
        /**
         * Puts it along the floor of the price pane, costing the price no height.
         *
         * @param heightRatio - How much of the pane's floor it takes.
         * @returns The finished draft.
         */
        alongTheFloor(heightRatio?: number): PlanDraft;
        private add;
        private reviseLast;
        private finish;
    }
    /**
     * Starts a plan over a window of bars.
     *
     * @param bars - The window being drawn, which every series lines up with.
     * @returns A builder bound to those instants.
     */
    export declare function plotOver(bars: PriceBarWindow): PlotBuilder;

    // price-bar.d.ts
    /**
     * One open-high-low-close bar, carrying what built it.
     *
     * From the venue where the venue publishes one, and from the recorded book mid
     * below a minute, where no venue does. The two disagree by half a spread —
     * inside one price bucket on any contract worth charting — and a bar says which
     * it is only through \`expectedFrames\`, which a venue candle has no notion of.
     */
    export interface PriceBar {
        /** Bucket edges. Always aligned; a bucket the query range clipped is never emitted. */
        readonly openedAtMs: number;
        readonly closedAtMs: number;
        readonly openPrice: number;
        readonly highPrice: number;
        readonly lowPrice: number;
        readonly closePrice: number;
        /**
         * What traded inside the bucket, by which side crossed the spread.
         *
         * Zero is a real answer: a bucket the book was recorded through with nobody
         * trading is a quiet bucket, not a missing one.
         */
        readonly buyVolume: number;
        readonly sellVolume: number;
        readonly tradeCount: number;
        /**
         * Frames a wholly recorded bucket of this width holds.
         *
         * A bar short of them was built from less than it should have been, which
         * is a different fact from a bar still being built.
         */
        readonly expectedFrames: number;
        /** Frames that actually landed. Below \`expectedFrames\` on a closed bar, the bar is partial. */
        readonly frameCount: number;
        /**
         * False while the bucket can still grow.
         *
         * Without it, a short \`frameCount\` conflates two different facts: a bucket
         * the collector missed seconds of, and one that has simply not finished.
         */
        readonly isClosed: boolean;
        /** Later than \`openedAtMs\` when a gap straddles the bar's opening. */
        readonly firstFrameAtMs: number;
        readonly lastFrameAtMs: number;
    }
    /** A run of bars on one declared interval, oldest first. Absent buckets are omitted. */
    export interface PriceBarWindow {
        readonly instrumentSymbol: string;
        /** Declared by the caller and honoured exactly; no surface width may influence it. */
        readonly intervalMs: number;
        readonly warmupBarsRequested: number;
        /** What the archive could supply. Below the request, the output is still converging. */
        readonly warmupBarsReturned: number;
        readonly bars: readonly PriceBar[];
    }
    export interface PriceBarQuery {
        readonly symbol: string;
        readonly fromMs: number;
        readonly toMs: number;
        readonly intervalMs: number;
        /** Bars before \`fromMs\`, at the same interval. Costs rows, never columns. */
        readonly warmupBars: number;
    }
    /** A window that holds nothing, for a chart that has not loaded one yet. */
    /** How much of a bar's own width was recorded, and whether that is settled yet. */
    export type BarCompleteness = 'forming' | 'partial' | 'whole';
    /**
     * Reads a bar's completeness off what built it.
     *
     * @param bar - The bar to classify.
     * @returns Which of the three states it is in.
     */
    export declare function classifyBar(bar: PriceBar): BarCompleteness;
    /**
     * Bars are budgeted by what they scan and what they emit, never by the range asked for.
     *
     * A range is free to name a century; what it costs is bounded by the recording
     * that actually overlaps it.
     */
    export declare const BAR_BUDGET: {
        readonly maximumSourceFrames: 180000;
        readonly maximumBars: 2000;
    };
    /**
     * Trims a run of bars to what a window may return, keeping the newest.
     *
     * @param bars - Bars for the whole range, oldest first.
     * @returns At most the budgeted count, still oldest first.
     */

    // reading-words.d.ts
    /** The languages the interface is written in. */
    export type Locale = 'en' | 'pt-BR';
    /**
     * The same phrase in as many languages as its author wrote it in.
     *
     * English is required rather than optional: a phrase has to have something to
     * fall back to, and a fallback picked at random from whatever was supplied is
     * a phrase nobody chose.
     */
    export type Words = {
        readonly en: string;
    } & Partial<Record<Locale, string>>;
    /**
     * Sets the language readings answer in.
     *
     * The host's, not a reading's: a reading says what it is called, and the page
     * says which language it is being read in.
     *
     * @param locale - The language the interface is now in.
     */
    /**
     * One phrase in the language the page is being read in.
     *
     * @param words - The phrase, in every language its author wrote it in.
     * @returns The reader's language where the author supplied it, English otherwise.
     */
    export declare function inWords(words: Words): string;

    // series-math.d.ts
    /** A stretch of bars with no unrecorded time inside it. Half-open. */
    export interface BarSegment {
        readonly startIndex: number;
        readonly endIndex: number;
    }
    /**
     * What a smoothing pass needs, as one thing rather than five.
     *
     * Named rather than positional because three of the five were numbers in a row:
     * the period, the first index and the last. Two of them transposed compiles, and
     * every average on the chart would be a little wrong with nothing to show for it.
     */
    export interface SeriesFill {
        readonly source: ArrayLike<number>;
        readonly periodBars: number;
        /** The stretch to fill, which is a stretch recorded without interruption. */
        readonly segment: BarSegment;
        /** Written in place, and left untouched before the seed is complete. */
        readonly out: Float64Array;
    }
    /**
     * Splits bars into stretches that were recorded without interruption.
     *
     * Every indicator restarts at a boundary rather than carrying state across it.
     * Smoothing over a hole invents a trend through time nobody observed, and the
     * result is indistinguishable from a real one once it is a line on a screen.
     *
     * @param bars - The window, oldest first.
     * @returns The stretches, in order.
     */
    export declare function findContinuousSegments(bars: readonly PriceBar[]): BarSegment[];
    /**
     * The instant each bar is plotted at.
     *
     * @param bars - The window, oldest first.
     * @returns Close instants, ascending.
     */
    export declare function collectInstants(bars: readonly PriceBar[]): Float64Array;
    /**
     * An array of the given length with nothing said anywhere.
     *
     * @param length - How many vertices.
     * @returns All NaN, so an untouched position breaks the line.
     */
    export declare function createBlankValues(length: number): Float64Array;
    /**
     * Wilder's smoothing step.
     *
     * @param previous - The running average.
     * @param sample - The new observation.
     * @param periodBars - The period the average is over.
     * @returns The updated average.
     */
    export declare function smoothWilder(previous: number, sample: number, periodBars: number): number;
    /**
     * The exponential smoothing weight for a period.
     *
     * @param periodBars - Bars the average spans.
     * @returns The weight given to each new sample.
     */
    export declare function resolveExponentialWeight(periodBars: number): number;
    /**
     * Fills a stretch with an exponential average of a source series.
     *
     * Seeded with the simple mean of the first period rather than with the first
     * value. It is what the reference implementations do, and it is why an average
     * read off this chart and one read off another agree from the first bar either
     * of them draws rather than only after the seed has washed out.
     *
     * @param fill - The source, the period, the stretch, and where to write it.
     */
    export declare function fillExponential(fill: SeriesFill): void;
    /**
     * Fills a stretch with Wilder's smoothing of a source series.
     *
     * Seeded with the simple mean of the first period, which is the seed Wilder
     * defined and the one the reference implementations use.
     *
     * @param fill - The source, the period, the stretch, and where to write it.
     */
    export declare function fillWilder(fill: SeriesFill): void;
    /**
     * How far a bar travelled, counting the gap from where the last one closed.
     *
     * @param bar - The bar to measure.
     * @param previousClose - What the bar before it closed at.
     * @returns The true range, in quote currency.
     */
    export declare function resolveTrueRange(bar: PriceBar, previousClose: number): number;
    /**
     * How far each bar of a stretch travelled.
     *
     * @param bars - The window, oldest first.
     * @param segment - The unbroken stretch to measure.
     * @returns One range per bar, blank outside the stretch.
     */
    export declare function collectTrueRanges(bars: readonly PriceBar[], segment: BarSegment): Float64Array;

    // settled-sessions.d.ts
    /**
     * The newest coarser bar that had already closed, for each bar of a window.
     *
     * This is the whole of what reading a coarser rung honestly amounts to. A daily
     * level drawn on a minute chart is a level the day *before* agreed on, and the
     * day being drawn through has not finished having its say: taking the figures
     * off a bar that is still forming shows the reader, at nine in the morning,
     * something that will not be true until midnight.
     *
     * A bar closing exactly when a drawn bar opens counts as settled. That is the
     * instant it became knowable, and holding it back a bar would draw yesterday's
     * level a minute into today.
     *
     * @param bars - The window being drawn, oldest first.
     * @param higher - Bars of the coarser rung, oldest first.
     * @returns One entry per drawn bar, undefined where nothing had closed yet.
     */
    export declare function holdLastClosed(bars: readonly PriceBar[], higher: readonly PriceBar[]): readonly (PriceBar | undefined)[];
    /**
     * Aligns a coarser rung to the drawn bars, holding each back to what it knew.
     *
     * Run by the host, so a reading has nothing to remember to do and no raw
     * window to reach into.
     *
     * @param bars - The window being drawn.
     * @param higher - The coarser bars the archive supplied, or null where it had none.
     * @returns The sessions aligned to the drawn bars, with their turnovers marked.
     */
    /**
     * The sessions one reading declared, under the names it declared them with.
     *
     * @param bars - The window being drawn.
     * @param supplied - The coarser windows fetched for the chart, by rung.
     * @param declared - What this reading asked for.
     * @returns One entry per declared name, blank where the archive had no rung.
     */

    // venue-connector.d.ts
    /**
     * A connector: what a venue can do, and how to read what it says.
     *
     * Every method here is pure and synchronous, and every argument and return is
     * plain data. A connector holds no socket, no promise and no timer; it describes
     * a request and reads an answer, and the engine does the rest.
     *
     * That is not a matter of taste. The supervisor awaits each recording it tears
     * down, so a connector owning its own socket would own a close that can hang —
     * and one that never settles wedges the reconcile pass for every contract on the
     * machine, one bad connector stopping four good recordings.
     */
    /** How a request is made, for the few venues that will not answer a plain read. */
    export type RequestMethod = 'GET' | 'POST';
    /**
     * A request for the engine to perform.
     *
     * A description rather than a fetch: the connector never reaches the network
     * itself, so it cannot hang, cannot retry behind the engine's back, and cannot
     * send anything the engine did not see first.
     */
    export interface VenueRequest {
        readonly url: string;
        /** Omitted for the ordinary read, which is every listing and every candle. */
        readonly method?: RequestMethod;
        /** Sent as it stands, for a venue that asks to be posted to. */
        readonly body?: string;
        readonly headers?: Readonly<Record<string, string>>;
    }
    /**
     * How fast the engine may ask this venue for things.
     *
     * The one thing about a venue that only its own connector can know. A rate
     * limit is published per exchange, in that exchange's units, so a figure picked
     * in the engine is a guess that is wrong for everybody: too high and the venue
     * refuses the whole listing rather than the page it landed on, too low and a
     * reader waits through round trips the venue would have answered together.
     *
     * Inherited from the base class, so a connector writes this only where its
     * venue differs from the shipped ones.
     */
    export interface VenuePacing {
        /**
         * Most pages the engine asks a listing for before it stops asking.
         *
         * A ceiling rather than a race: a venue that always answers with another
         * page is one whose listing never returns.
         */
        readonly pagesPerListing: number;
        /** How many requests may be in the air at this venue at once. */
        readonly requestsAtOnce: number;
    }
    /**
     * What the shipped venues tolerate, and what a connector gets for saying nothing.
     */
    /** A socket to open, and what to say once it is open. */
    export interface VenueStreamPlan {
        readonly url: string;
        /**
         * What to send on connecting, where the venue needs to be asked.
         *
         * Empty for a venue that takes its subscription in the URL.
         */
        readonly greetings?: readonly string[];
        /**
         * What to send periodically to be left connected.
         *
         * Null where the venue's own pings are enough. The engine owns the timer.
         */
        readonly heartbeat?: {
            readonly everyMs: number;
            readonly send: string;
        } | null;
    }
    /** One instrument, as a venue lists it. */
    export interface VenueInstrument {
        /** What the venue calls it, which is what every later request repeats back. */
        readonly symbol: string;
        readonly base: string;
        readonly quote: string;
        /**
         * The smallest price move the venue quotes.
         *
         * Carried because the chart buckets prices, and a bucket finer than the tick
         * draws a ladder of stripes with nothing between them.
         */
        readonly priceStep: number;
        /** False for a listing that exists but is halted, delisted, or not yet open. */
        readonly isTrading: boolean;
    }
    /**
     * One candle, with the venue's own opt-outs in it.
     *
     * Null rather than zero wherever the venue publishes nothing: zero is a real
     * answer here — a bucket nobody traded in is a quiet bucket — so a venue that
     * counts no prints has to be distinguishable from one whose bar was quiet, or
     * the difference is written flat across its whole history.
     *
     * Whether the bar has closed is deliberately absent: that is a comparison
     * against now, and a connector holds no clock.
     */
    export interface VenueBar {
        readonly openedAtMs: number;
        readonly closedAtMs: number;
        readonly openPrice: number;
        readonly highPrice: number;
        readonly lowPrice: number;
        readonly closePrice: number;
        readonly volume: number | null;
        /** What crossed the spread upward, where the venue splits its volume. */
        readonly buyVolume: number | null;
        readonly tradeCount: number | null;
    }
    /** One page of candles asked for. */
    export interface BarPageRequest {
        readonly symbol: string;
        readonly widthMs: number;
        readonly fromMs: number;
        readonly toMs: number;
        readonly limit: number;
    }
    /**
     * Everything the engine needs to read one venue.
     *
     * Flat, and every method on the connector itself. The methods a venue does not
     * have are the ones its declaration says \`null\` for, and the base class answers
     * those by refusing — so there is one place a capability is claimed, and
     * registration checks the methods against it.
     */
    export interface VenueConnector {
        readonly declaration: VenueDeclaration;
        /** How fast this venue may be asked; the base class answers for most. */
        readonly pacing: VenuePacing;
        /**
         * Every venue lists what it trades; there is nothing to chart otherwise.
         *
         * @param from - How many instruments come before the page being asked for,
         *               nought for the first. Ignored by a venue that serves its
         *               listing whole, which is most of them.
         */
        planInstruments: (from: number) => VenueRequest;
        /**
         * @param payload - Whatever the venue answered, already parsed from JSON.
         * @returns Every instrument this page listed.
         * @throws Error when the answer is not the shape the connector expects.
         */
        readInstruments: (payload: unknown) => readonly VenueInstrument[];
        /**
         * How many instruments the venue says it lists in all.
         *
         * The difference between a listing read one page at a time and one read at
         * once: knowing the total, the engine asks for every remaining page
         * together rather than waiting for each to name the next.
         *
         * @param payload - The first page, as it arrived.
         * @returns The count, or null where the venue does not publish one.
         */
        readInstrumentTotal: (payload: unknown) => number | null;
        /**
         * The next page, for a venue whose pages can only be reached in order.
         *
         * The other shape of paging: a cursor the venue hands out with each page,
         * which cannot be guessed and so cannot be asked for in parallel.
         *
         * @param payload - The page just read.
         * @param read - How many instruments have been gathered so far.
         * @returns What to fetch next, or null once the listing is whole.
         */
        continueInstruments: (payload: unknown, read: number) => VenueRequest | null;
        /**
         * What the venue itself matches against a reader's typing.
         *
         * Where a venue offers this, a reader searching a listing that is still
         * arriving gets the venue's own answer instead of a search across the part
         * that happens to have loaded.
         *
         * @param term - What the reader typed, trimmed and not empty.
         * @returns The request, read by \`readInstruments\`, or null where the venue
         *          offers no such endpoint — which is most of them.
         */
        planInstrumentSearch: (term: string) => VenueRequest | null;
        /**
         * One socket carrying everything the venue streams.
         *
         * One rather than one per capability, because that is how venues sell it:
         * a book and a tape on separate sockets is two connections against a limit
         * that is usually counted per address, and two independent reconnects whose
         * gaps do not line up in the ledger.
         *
         * @param symbol - The instrument being recorded.
         * @param ticket - What \`readStreamTicket\` returned, or empty where the venue
         *                 needs none.
         */
        planStream: (symbol: string, ticket: string) => VenueStreamPlan;
        /**
         * The request that buys a socket, for a venue handing them out per session.
         *
         * @returns The request, or null for a venue whose socket URL is fixed.
         */
        planStreamTicket: () => VenueRequest | null;
        /**
         * @param payload - What that request answered.
         * @returns Whatever \`planStream\` needs to build its URL — usually a token.
         */
        readStreamTicket: (payload: unknown) => string;
        planSnapshot: (symbol: string) => VenueRequest;
        readSnapshot: (payload: unknown) => DepthSnapshot;
        /**
         * @param payload - One message off the socket, already parsed.
         * @returns The change it carried, or null for anything else on the stream.
         */
        readUpdate: (payload: unknown) => DepthDiff | null;
        /**
         * @param payload - One message off the socket, already parsed.
         * @returns Every print it carried, empty for anything else on the stream.
         */
        readTrades: (payload: unknown) => readonly ExecutedTrade[];
        planBars: (request: BarPageRequest) => VenueRequest;
        /**
         * @param payload - The venue's answer, already parsed from JSON.
         * @param request - What was asked for, handed back because most venues name
         *                  only where a candle opens, and the width is what turns
         *                  that into the first instant it does not hold.
         * @returns The candles it carried, oldest first.
         */
        readBars: (payload: unknown, request: BarPageRequest) => readonly VenueBar[];
    }
    /**
     * Where a connector contradicts itself.
     *
     * Checked when it is registered rather than when a recording starts, because the
     * second is hours later, on a machine nobody is watching, and the contradiction
     * was already in the file.
     *
     * The declaration is what claims; the methods are what can answer. A venue that
     * declares a book and never wrote the methods behind one is a chart waiting for
     * a message that never comes, and a venue with the methods and no declaration is
     * one quietly doing more than the chart was told to expect.
     *
     * @param connector - The connector being registered.
     * @returns One sentence per contradiction, empty where there are none.
     */
    /**
     * Where a connector asks to be paced in a way the engine will not perform.
     *
     * Read at registration beside the contradictions, and for the same reason: a
     * listing capped at nought pages fetches nothing, and the reader finds out when
     * the chart stays empty rather than when the file was written.
     *
     * @param connector - The connector being registered.
     * @returns One sentence per fault, empty where there are none.
     */
    /**
     * What a connector is written as.
     *
     * Methods on the class, not objects of functions hung off it. Every one a venue
     * does not have is inherited from here and refuses, so a connector is only as
     * long as what its venue can actually answer — and the declaration stays the one
     * place a capability is claimed.
     *
     * It also carries the two readings every connector repeats: a figure a venue
     * sent as text, and a list that has to be somewhere in the answer.
     */
    export declare abstract class Connector implements VenueConnector {
        abstract readonly declaration: VenueDeclaration;
        /** What the shipped venues tolerate, until a connector says otherwise. */
        readonly pacing: VenuePacing;
        abstract planInstruments(from: number): VenueRequest;
        abstract readInstruments(payload: unknown): readonly VenueInstrument[];
        /**
         * How many the venue says it lists. None said, unless a connector says so.
         *
         * @returns Null, which is a listing whose length is only known by reading it.
         */
        readInstrumentTotal(payload: unknown): number | null;
        /**
         * The next page of the listing. One page, unless a connector says otherwise.
         *
         * @returns Null, which is a listing served whole.
         */
        continueInstruments(payload: unknown, read: number): VenueRequest | null;
        /**
         * What the venue matches against typing. Nothing, unless it offers it.
         *
         * @returns Null, which is a venue whose listing is searched where it lands.
         */
        planInstrumentSearch(term: string): VenueRequest | null;
        /**
         * The socket to open.
         *
         * @returns Never; a venue declaring no book and no tape streams nothing.
         * @throws Error, because nothing should have asked.
         */
        planStream(symbol: string, ticket: string): VenueStreamPlan;
        /**
         * The request that buys a socket. None, unless a connector says otherwise.
         *
         * @returns Null, which is a socket whose URL is fixed.
         */
        planStreamTicket(): VenueRequest | null;
        /**
         * What a ticket request answered. Nothing, for a venue that needs none.
         *
         * @returns The empty string.
         */
        readStreamTicket(payload: unknown): string;
        /**
         * Where the resting ladder is fetched from.
         *
         * @returns Never; a venue declaring no book has none to fetch.
         * @throws Error, because nothing should have asked.
         */
        planSnapshot(symbol: string): VenueRequest;
        /**
         * The ladder out of that answer.
         *
         * @returns Never, for the same reason.
         * @throws Error, because nothing should have asked.
         */
        readSnapshot(payload: unknown): DepthSnapshot;
        /**
         * One book update off the socket.
         *
         * @returns Null, which is how every message that is not one is answered.
         */
        readUpdate(payload: unknown): DepthDiff | null;
        /**
         * The prints one message carried.
         *
         * @returns None, which is how every message carrying none is answered.
         */
        readTrades(payload: unknown): readonly ExecutedTrade[];
        /**
         * Where one page of candles is fetched from.
         *
         * @returns Never; a venue declaring no bars serves none.
         * @throws Error, because nothing should have asked.
         */
        planBars(request: BarPageRequest): VenueRequest;
        /**
         * The candles out of that answer.
         *
         * @returns Never, for the same reason.
         * @throws Error, because nothing should have asked.
         */
        readBars(payload: unknown, request: BarPageRequest): readonly VenueBar[];
        /**
         * An address, built rather than spelled out.
         *
         * Through \`URL\` and its own query, because a URL joined by hand is a URL
         * with a reader's symbol pasted into it unescaped — and because the pieces
         * are easier to read down a list than inside one long sum of strings.
         *
         * @param base - The venue's origin, as its own constant.
         * @param path - The endpoint, from the root.
         * @param query - What to ask for, in the order given. An entry left
         *                undefined is left out, so an optional parameter needs no
         *                branch around it.
         * @returns The whole address.
         */
        protected address(base: string, path: string, query?: Readonly<Record<string, string | number | undefined>>): string;
        /**
         * A figure as a number, or null where it does not read as one.
         *
         * Null rather than NaN or zero: a price that reads as NaN is written as a
         * real print and no later read can tell it from one, and zero is a real
         * answer everywhere a venue publishes figures.
         *
         * @param field - Whatever arrived in that position.
         * @returns The number, or null.
         */
        protected readNumber(field: unknown): number | null;
        /**
         * A list out of a venue's answer, or a refusal saying it sent none.
         *
         * @param payload - What the venue answered, already parsed from JSON.
         * @param at - The field the list is under, or absent where it is the answer.
         * @returns The entries, unread.
         * @throws Error when there is no list where the connector said there is one.
         */
        protected requireList(payload: unknown, at?: string): readonly unknown[];
    }

    // venue-plan.d.ts
    /**
     * What a venue can and cannot do, said by whoever connected to it.
     *
     * The other half of the idea an indicator already follows: what the host has to
     * know is said by the one who knows it, before anything is fetched or drawn.
     */
    /** How trustworthy the ordering of one venue's book updates is. */
    export type BookGrade =
    /** Every update names the one before it. The strongest check there is. */
    'linked'
    /** Every update covers a span, and the spans have to meet. */
     | 'ranged'
    /** Every update is one past the last. Weaker, but checkable. */
     | 'stepped'
    /** Nothing in the update says where it sits. Nothing is checkable. */
     | 'unsequenced';
    /** Whose clock an event carries. */
    export type EventClock =
    /** The venue stamped it. */
    'venue'
    /** Nothing stamped it, so the engine stamps arrival and counts that it did. */
     | 'arrival';
    /** Whether the tape says which side crossed the spread. */
    export type TapeSiding = 'sided' | 'unsided';
    /**
     * What the venue publishes of the resting book.
     *
     * Null on a venue that publishes none. The heatmap is then not offered for that
     * instrument at all — not offered and drawn black, because black already means
     * a price nothing rests at, and reusing it for "nobody said" is the invention
     * the gap ledger exists to prevent.
     */
    export interface BookCapability {
        readonly grade: BookGrade;
        /**
         * Levels published per side, or every one of them.
         *
         * The most consequential line in the declaration. In a whole ladder an
         * absent price means nothing rests there; in a feed of fifty it means
         * nobody said. It also changes how the mirror is kept: a windowed feed
         * never sends a removal for a level that merely fell out of the window, so
         * the engine trims to this rank after every update. Without the trim, a
         * level a fast move pushed past the edge stands in the recording for hours
         * at the size it last had — a solid shelf that stopped existing when the
         * move started.
         */
        readonly levelsPerSide: number | 'all';
        /** How often the venue publishes at its fastest, which floors the frame clock. */
        readonly publishIntervalMs: number;
        readonly clock: EventClock;
    }
    /**
     * What the venue publishes of what actually traded.
     *
     * Null where it publishes nothing.
     */
    export interface TapeCapability {
        readonly siding: TapeSiding;
        readonly clock: EventClock;
        /**
         * Whether prints carry an id that survives a replay.
         *
         * A resubscribe replays the last prints on several venues, and without an
         * id the engine cannot tell a replayed print from a new one — so the open
         * bucket double-counts while the closed ones vanish under the archive's own
         * conflict rule, over- and under-counting in the same breath.
         */
        readonly hasStableIds: boolean;
    }
    /**
     * One bar width the venue serves, and the phase its buckets open on.
     *
     * A pair rather than a number because of the anchor. A width alone assumes
     * every bucket opens on the epoch, and no venue's weekly bar starts on a
     * Thursday, which is where the epoch puts one. A width with the wrong phase
     * folds bars into a day whose boundary is hours out, silently, inside the
     * settled-session walk every multi-timeframe reading goes through.
     */
    export interface BarRung {
        readonly widthMs: number;
        /** Milliseconds past the epoch that a bucket of this width opens on. */
        readonly anchorMs: number;
    }
    /**
     * What the venue serves of the past, and at which widths.
     *
     * Null where it serves none, and the engine then folds every bar itself out of
     * what it is recording.
     */
    export interface BarCapability {
        /** Widths served. A rung not here is dropped, not raised. */
        readonly rungs: readonly BarRung[];
        /** Bars one request may return, which is the venue's own cap. */
        readonly barsPerRequest: number;
        readonly hasVolume: boolean;
        /**
         * Whether the candle splits its volume by the side that crossed.
         *
         * False is the ordinary case. One venue of any size publishes it, which is
         * why five shipped readings quietly assume every venue does — and why a
         * tape that names the aggressor buys those readings nothing over history,
         * where the bars come from here.
         */
        readonly hasBuyVolume: boolean;
        /**
         * Whether the candle counts its prints.
         *
         * Zero is a real answer everywhere else here — a bucket nobody traded in is
         * a quiet bucket — so a venue publishing no count has to say so rather than
         * have zero written across its whole history.
         */
        readonly hasTradeCount: boolean;
    }
    /**
     * Everything a venue can and cannot do, in the connector's own words.
     *
     * Every field is required and every capability is \`T | null\`. There is no
     * optional property here on purpose: an author has to write \`null\` to say no,
     * and writing it is the moment they read what the engine does instead. A
     * forgotten flag defaulting to yes is a connector that lies into an archive
     * that cannot be written twice; one defaulting to no is a chart quietly drawing
     * less than it could, for ever, with nobody told why.
     */
    export interface VenueDeclaration {
        readonly book: BookCapability | null;
        readonly tape: TapeCapability | null;
        readonly bars: BarCapability | null;
    }
    /**
     * A fact about the venue that a reading cannot be computed without.
     *
     * The same idea as an indicator naming the rungs it reads, one level up.
     */
    export type VenueFact =
    /** Resting size per price, at all. */
    'book'
    /** Every resting price, not a window onto the nearest few. */
     | 'wholeBook'
    /** What actually traded. */
     | 'tape'
    /** How much traded in a bar, either side of the spread. */
     | 'volume'
    /** Volume split by the side that crossed the spread. */
     | 'takerSplit'
    /** How many prints made a bar. */
     | 'tradeCount';
    /**
     * Which of those facts a venue actually supplies.
     *
     * The taker split is read off the bars rather than off the tape. Five of the
     * shipped readings compute over the drawn bars, and outside the shipped venue
     * no candle endpoint carries a split — so a sided tape grants the fact only
     * where the bars are folded from that tape. Granting it off the tape alone
     * would draw cumulative delta correct over the collector's uptime and blank
     * before it, with the seam moving on every restart.
     *
     * @param declaration - What the connector declared.
     * @returns The facts a reading may rely on.
     */
    /**
     * The facts a reading asked for that the venue does not supply.
     *
     * @param needed - What the reading declared it reads.
     * @param offered - What the venue was found to supply.
     * @returns The shortfall, in the order the reading named it.
     */
}
`;
